/*
 * Copyright 2026 Ivan Ponomarev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ru.curs.hurdygurdy.spec;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.media.Schema;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import static ru.curs.hurdygurdy.spec.SchemaSemantics.CLASS_NAME_PATTERN;
import static ru.curs.hurdygurdy.spec.SchemaSemantics.FILE_NAME_PATTERN;
import static ru.curs.hurdygurdy.spec.SchemaSemantics.extractGroup;
import static ru.curs.hurdygurdy.spec.SchemaSemantics.isPolymorphicInterface;

/**
 * What a schema inherits through {@code allOf}, and which of its properties are
 * therefore its own.
 *
 * <p>Resolving an {@code allOf} chain is the same question in every target
 * language: walk the {@code $ref} parents, keep the first declaration of each
 * key, and never let the discriminator property through as data. It was
 * nevertheless written out three times — {@code inheritedPropertyKeys} and
 * {@code inheritedComponents}/{@code componentsOfRef} in the Java definer, and
 * {@code constructorPropertiesOf} in the Kotlin one — and the local lookup they
 * all need four times over.
 *
 * <p>Only same-file references are followed. A parent in another file is
 * generated by that file's own run, where its properties are visible; from here
 * its schema is not, so the subtype simply inherits nothing and says so by
 * omission rather than by guessing.
 */
public final class SchemaInheritance {

    private SchemaInheritance() {
    }

    /**
     * One property a generated type declares, wherever it was declared in the
     * {@code allOf} chain.
     *
     * @param key      the property name as written in the specification
     * @param schema   its schema
     * @param required whether the declaring object lists it as required
     */
    public record InheritedProperty(String key, Schema<?> schema, boolean required) {
    }

    /**
     * The document's component schemas, empty when it declares none.
     *
     * @param openAPI the document to read
     * @return name to schema
     */
    public static Map<String, Schema> componentSchemas(OpenAPI openAPI) {
        return Optional.ofNullable(openAPI.getComponents())
                .map(Components::getSchemas)
                .orElse(Collections.emptyMap());
    }

    /**
     * The component a same-file {@code $ref} names, or null when the reference
     * points into another file or names nothing.
     *
     * @param openAPI the document the reference was written in
     * @param ref     the reference to resolve
     * @return the referenced component, or null
     */
    public static Schema<?> localComponent(OpenAPI openAPI, String ref) {
        if (!extractGroup(ref, FILE_NAME_PATTERN).isBlank()) {
            return null;
        }
        return componentSchemas(openAPI).get(extractGroup(ref, CLASS_NAME_PATTERN));
    }

    /**
     * The member of an {@code allOf} that carries the schema's own properties —
     * the one that is not a {@code $ref} — or the schema itself when it is not a
     * composition.
     *
     * @param schema the schema to unwrap
     * @return the member carrying its own properties
     */
    public static Schema<?> ownSchemaOf(Schema<?> schema) {
        if (schema.getOneOf() != null || schema.getAllOf() == null) {
            return schema;
        }
        Schema<?> own = schema;
        for (Schema<?> member : schema.getAllOf()) {
            if (member.get$ref() == null) {
                own = member;
            }
        }
        return own;
    }

    /**
     * The properties declared directly on a schema, in declaration order,
     * excluding the one its own discriminator manages.
     *
     * <p>Jackson writes the discriminator as the {@code @JsonTypeInfo} type id on
     * the generated base, so carrying it as data as well would put it on the wire
     * twice.
     *
     * @param schema the schema to read
     * @return its own properties, in declaration order
     */
    public static List<InheritedProperty> ownProperties(Schema<?> schema) {
        List<InheritedProperty> result = new ArrayList<>();
        Map<String, Schema> properties = schema.getProperties();
        if (properties == null) {
            return result;
        }
        Set<String> required = schema.getRequired() == null
                ? Set.of() : new HashSet<>(schema.getRequired());
        String discriminator = discriminatorProperty(schema);
        for (Map.Entry<String, Schema> e : properties.entrySet()) {
            if (!e.getKey().equals(discriminator)) {
                result.add(new InheritedProperty(e.getKey(), e.getValue(), required.contains(e.getKey())));
            }
        }
        return result;
    }

    /**
     * Everything a schema inherits from its {@code allOf} {@code $ref} parents,
     * most-base first, each key kept only the first time it is seen.
     *
     * <p>A property can be restated at several levels of a chain — the YouTrack
     * specification does it on every subtype — and first-wins is what keeps the
     * generated parameter list aligned with the base's, which is what a subclass
     * forwards its super-constructor arguments to.
     *
     * @param schema  the schema to read
     * @param openAPI the document it was declared in
     * @return the inherited properties, most-base first
     */
    public static List<InheritedProperty> inheritedProperties(Schema<?> schema, OpenAPI openAPI) {
        List<InheritedProperty> result = new ArrayList<>();
        if (schema.getOneOf() != null || schema.getAllOf() == null) {
            return result;
        }
        Set<String> seen = new HashSet<>();
        for (Schema<?> member : schema.getAllOf()) {
            if (member.get$ref() != null) {
                for (InheritedProperty property : flattenedPropertiesOf(member.get$ref(), openAPI)) {
                    if (seen.add(property.key())) {
                        result.add(property);
                    }
                }
            }
        }
        return result;
    }

    /**
     * Every property a generated type declares: what it inherits, then what it
     * adds, each key once.
     *
     * @param schema  the schema to read
     * @param openAPI the document it was declared in
     * @return the flattened properties, in declaration order
     */
    public static List<InheritedProperty> flattenedProperties(Schema<?> schema, OpenAPI openAPI) {
        List<InheritedProperty> result = new ArrayList<>(inheritedProperties(schema, openAPI));
        Set<String> seen = new HashSet<>();
        for (InheritedProperty property : result) {
            seen.add(property.key());
        }
        // The schema's OWN discriminator has to be stripped here rather than in
        // ownProperties: when the schema is an intermediate base, ownSchemaOf
        // unwraps it to the inline allOf member, whose discriminator is null.
        String discriminator = discriminatorProperty(schema);
        for (InheritedProperty property : ownProperties(ownSchemaOf(schema))) {
            if (!property.key().equals(discriminator) && seen.add(property.key())) {
                result.add(property);
            }
        }
        return result;
    }

    /**
     * Every property key a schema contributes — its own and its {@code allOf}
     * ancestors' — with the discriminator included.
     *
     * <p>Unlike {@link #flattenedProperties}, this is about which names a subtype
     * must not re-declare, and the discriminator is one of them.
     *
     * @param schema  the schema to read
     * @param openAPI the document it was declared in
     * @return every property key the schema contributes
     */
    public static Set<String> allPropertyKeys(Schema<?> schema, OpenAPI openAPI) {
        Set<String> keys = new LinkedHashSet<>();
        Schema<?> own = schema;
        if (schema.getOneOf() == null && schema.getAllOf() != null) {
            for (Schema<?> member : schema.getAllOf()) {
                if (member.get$ref() != null) {
                    Schema<?> parent = localComponent(openAPI, member.get$ref());
                    if (parent != null) {
                        keys.addAll(allPropertyKeys(parent, openAPI));
                    }
                } else {
                    own = member;
                }
            }
        }
        if (own.getProperties() != null) {
            keys.addAll(own.getProperties().keySet());
        }
        return keys;
    }

    /**
     * Whether a same-file {@code allOf} parent is generated as an interface — a
     * discriminator base or a {@code oneOf} container — rather than a concrete
     * type. A parent in another file is assumed to be one, since its schema is
     * not visible here.
     *
     * @param ref     the parent reference
     * @param openAPI the document the reference was written in
     * @return whether the parent is generated as an interface
     */
    public static boolean isInterfaceBase(String ref, OpenAPI openAPI) {
        if (!extractGroup(ref, FILE_NAME_PATTERN).isBlank()) {
            return true;
        }
        Schema<?> schema = localComponent(openAPI, ref);
        return schema != null
                && (schema.getDiscriminator() != null || isPolymorphicInterface(schema));
    }

    private static List<InheritedProperty> flattenedPropertiesOf(String ref, OpenAPI openAPI) {
        Schema<?> schema = localComponent(openAPI, ref);
        return schema == null ? List.of() : flattenedProperties(schema, openAPI);
    }

    private static String discriminatorProperty(Schema<?> schema) {
        return schema.getDiscriminator() == null ? null : schema.getDiscriminator().getPropertyName();
    }
}
